package hibernate;
// Generated 13-jul-2019 15:44:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String nombre;
     private String apellido;
     private String direccion;
     private String telefono;
     private String patente;
     private String vehiculo;
     private Set facturas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String nombre, String apellido, String patente, String vehiculo) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.patente = patente;
        this.vehiculo = vehiculo;
    }
    public Cliente(String nombre, String apellido, String direccion, String telefono, String patente, String vehiculo, Set facturas) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.telefono = telefono;
       this.patente = patente;
       this.vehiculo = vehiculo;
       this.facturas = facturas;
    }
    
    public Cliente(Integer idCliente, String nombre, String apellido, String direccion, String telefono, String patente, String vehiculo, Set facturas) {
       this.idCliente = idCliente;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.telefono = telefono;
       this.patente = patente;
       this.vehiculo = vehiculo;
       this.facturas = facturas;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getPatente() {
        return this.patente;
    }
    
    public void setPatente(String patente) {
        this.patente = patente;
    }
    public String getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(String vehiculo) {
        this.vehiculo = vehiculo;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


