package hibernate;
// Generated 13-jul-2019 15:44:13 by Hibernate Tools 4.3.1



/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private Cliente cliente;
     private String fecha;
     private String descripcion;
     private double importe;
     private double pago;
     private double deuda;
     private String entregado;

    public Factura() {
    }

    public Factura(Cliente cliente, String fecha, String descripcion, double importe, double pago, double deuda, String entregado) {
       this.cliente = cliente;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.importe = importe;
       this.pago = pago;
       this.deuda = deuda;
       this.entregado = entregado;
    }
    
    public Factura(Integer idFactura, Cliente cliente, String fecha, String descripcion, double importe, double pago, double deuda, String entregado) {
       this.idFactura = idFactura;
       this.cliente = cliente;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.importe = importe;
       this.pago = pago;
       this.deuda = deuda;
       this.entregado = entregado;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getImporte() {
        return this.importe;
    }
    
    public void setImporte(double importe) {
        this.importe = importe;
    }
    public double getPago() {
        return this.pago;
    }
    
    public void setPago(double pago) {
        this.pago = pago;
    }
    public double getDeuda() {
        return this.deuda;
    }
    
    public void setDeuda(double deuda) {
        this.deuda = deuda;
    }
    public String getEntregado() {
        return this.entregado;
    }
    
    public void setEntregado(String entregado) {
        this.entregado = entregado;
    }




}


